version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
  install:
    - requirements: requirements.txt
    - requirements: requirements_extra.txt
    - requirements: docs/source/requirements.txt
    - method: pip
      path: .

sphinx:
  configuration: docs/source/conf.py
  builder: html
  fail_on_warning: false
